# Generated by Django 3.1.1 on 2020-09-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='short',
            field=models.CharField(default='Description rapide et alléchante!', max_length=150),
        ),
    ]
