# Generated by Django 3.1.1 on 2020-09-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200930_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
