# Generated by Django 3.1.1 on 2020-09-30 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200930_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosage',
            name='unite',
        ),
    ]
