# Generated by Django 3.1.1 on 2020-10-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20201004_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='categorie',
            field=models.CharField(choices=[('legume', '🥕 Légume'), ('fruit', '🍒 Fruit'), ('feculent', '🌾 Féculent'), ('viande', '🍗 Viande'), ('poisson', '🐟 Poisson'), ('laitage', '🥛 Laitage'), ('boisson', '🍺 Boisson'), ('autre', '⭐️ Autre'), ('inconnu', '❌ Inconnu')], default='inconnu', max_length=25),
        ),
    ]
