# Generated by Django 3.1.1 on 2020-10-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20201004_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recette',
            name='description',
            field=models.CharField(help_text='Description rapide et alléchante!', max_length=150),
        ),
    ]
