# Generated by Django 3.1.1 on 2020-10-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20201008_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosage',
            name='unite',
            field=models.CharField(choices=[('g', 'grammes'), ('mL', 'millilitres'), ('cas', 'cuillère à soupe'), ('cac', 'cuillère à cafe'), ('pincee', 'pincée'), ('t', 'tranches'), ('u', 'unite')], default='u', max_length=20),
        ),
    ]
