# Generated by Django 3.1.1 on 2020-10-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20201009_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='name',
            field=models.CharField(help_text='Concis. Majuscule seulement au début.', max_length=100, unique=True, verbose_name='Nom'),
        ),
    ]
