# Generated by Django 3.1.1 on 2020-10-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20201028_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='image',
            field=models.CharField(default='empty', help_text="url de l'image à afficher,             stockée en local (recette ajoutée par le bot)", max_length=100),
        ),
        migrations.AlterField(
            model_name='recette',
            name='image_web',
            field=models.CharField(default=('https://paleomg.com/wp-content/plugins/simple-recipe-pro            /assets/placeholder.png',), help_text="url à afficher, si l'image n'est pas disponible             sur le serveur", max_length=100),
        ),
    ]
