# Generated by Django 3.1.1 on 2020-11-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0030_auto_20201028_2312"),
    ]

    operations = [
        migrations.AddField(
            model_name="recette",
            name="difficulte",
            field=models.PositiveSmallIntegerField(
                default=3, help_text="1:facile - 5:dur"
            ),
        ),
        migrations.AddField(
            model_name="recette",
            name="ponderation",
            field=models.PositiveSmallIntegerField(
                default=3, help_text="1:rare - 5:fréquent"
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="categorie",
            field=models.CharField(
                choices=[
                    ("legume", "🥕 Légume"),
                    ("fruit", "🍒 Fruit"),
                    ("feculent", "🌾 Féculent"),
                    ("epice", "🌶 Épice"),
                    ("viande", "🍗 Viande"),
                    ("poisson", "🐟 Poisson"),
                    ("laitage", "🥛 Laitage"),
                    ("sucre", "🍬 Sucré"),
                    ("sauce", "🥣 Sauce"),
                    ("pain", "🥖 Pain"),
                    ("autre", "⭐️ Autre"),
                    ("inconnu", "❌ Inconnu"),
                ],
                default="inconnu",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="recette",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Description rapide et alléchante ! Style libre",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="recette",
            name="image",
            field=models.CharField(
                default="empty",
                help_text="url de l'image à afficher,             stockée en local (recette ajoutée par le bot)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="recette",
            name="image_web",
            field=models.CharField(
                default=(
                    "https://paleomg.com/wp-content/plugins/simple-recipe-pro            /assets/placeholder.png",
                ),
                help_text="url à afficher, si l'image n'est pas disponible             sur le serveur",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="recette",
            name="name",
            field=models.CharField(
                help_text='Concis. Pas de "recette originale" ou autre style.',
                max_length=100,
                unique=True,
                verbose_name="Nom",
            ),
        ),
    ]
