# Generated by Django 3.1.1 on 2020-11-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0033_auto_20201106_0008"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recette",
            name="cooking_time",
            field=models.PositiveSmallIntegerField(
                default=15,
                help_text="Temps total (cuisson + préparation)",
                verbose_name="Temps passé en cuisine",
            ),
        ),
    ]
