# Generated by Django 3.1.1 on 2020-11-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0034_auto_20201106_0011"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recette",
            name="difficulte",
        ),
        migrations.AddField(
            model_name="recette",
            name="difficulty",
            field=models.PositiveSmallIntegerField(
                default=3, help_text="1 : facile / 5 : dur", verbose_name="Difficulté"
            ),
        ),
        migrations.AlterField(
            model_name="recette",
            name="ponderation",
            field=models.PositiveSmallIntegerField(
                default=3, help_text="1 : rare / 5 : fréquemment recommandé"
            ),
        ),
    ]
