# Generated by Django 3.1.1 on 2021-01-06 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20201106_0015'),
        ('app', '0031_auto_20201029_0747'),
    ]

    operations = [
    ]
