# Generated by Django 3.1.1 on 2020-09-30 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='is_vegetarian',
            new_name='vegetarian',
        ),
    ]
