# Generated by Django 3.1.1 on 2020-09-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200930_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='recettes',
            field=models.ManyToManyField(blank=True, related_name='recettes', to='app.Recette'),
        ),
    ]
