# Generated by Django 3.1.1 on 2020-10-04 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200930_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recette',
            old_name='description',
            new_name='instructions',
        ),
    ]
