# Generated by Django 3.1.1 on 2020-10-04 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201004_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recette',
            old_name='short',
            new_name='description',
        ),
    ]
