# Generated by Django 3.1.1 on 2020-10-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201004_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='categorie',
            field=models.CharField(choices=[('legume', '🥕 Légume'), ('fruit', '🍒 Fruit'), ('viande', '🍗 Viande'), ('poisson', '🐟 Poisson'), ('laitage', '🥛 Laitage'), ('boisson', '🍺 Boisson'), ('autre', '⭐️ Autre'), ('inconnu', '❌ Inconnu')], default='autre', max_length=25),
        ),
    ]
