# Generated by Django 3.1.1 on 2020-10-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20201004_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='desert',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='categorie',
            field=models.CharField(choices=[('legume', '🥕 Légume'), ('fruit', '🍒 Fruit'), ('feculent', '🌾 Féculent'), ('epice', '🌶 Épice'), ('viande', '🍗 Viande'), ('poisson', '🐟 Poisson'), ('laitage', '🥛 Laitage'), ('sucre', '🍬 Sucre'), ('sauce', '🥣 Sauce'), ('autre', '⭐️ Autre'), ('inconnu', '❌ Inconnu')], default='inconnu', max_length=25),
        ),
    ]
