# Generated by Django 3.1.1 on 2020-10-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20201006_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='pour',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='recette',
            name='preparation_time',
            field=models.PositiveSmallIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recette',
            name='desert',
            field=models.BooleanField(default=False, verbose_name='Dessert'),
        ),
    ]
