# Generated by Django 3.1.1 on 2020-10-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20201006_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='image',
            field=models.CharField(default='empty', help_text="url de l'image à afficher. Est stockée en local.", max_length=100),
        ),
    ]
