# Generated by Django 3.1.1 on 2020-10-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_auto_20201012_1241"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recette",
            name="desert",
        ),
        migrations.AddField(
            model_name="recette",
            name="categorie",
            field=models.CharField(
                choices=[
                    ("entree", "Entrée"),
                    ("plat", "Plat"),
                    ("dessert", "Dessert"),
                ],
                default="plat",
                max_length=25,
            ),
        ),
    ]
