# Generated by Django 3.1.1 on 2020-10-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_auto_20201028_1916"),
    ]

    operations = [
        migrations.AddField(
            model_name="recette",
            name="image_web",
            field=models.CharField(
                default="https://paleomg.com/wp-content/plugins/simple-recipe-pro/assets/placeholder.png",
                help_text="url de l'image à afficher, si l'image n'est pas disponible sur le serveur. Doit commencer par https://",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="recette",
            name="image",
            field=models.CharField(
                default="empty",
                help_text="url de l'image à afficher. Est stockée en local si la recette a été rajoutée par le bot.",
                max_length=100,
            ),
        ),
    ]
