name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create local settings placeholder
      run: |
        echo "secret_key= 'beeeeaaaaazzzzzerrrrraaaaaaaaaaaaaaaaaaaaaaaaaaaaam' " > recettes/local_settings.py
        echo "DEBUG_=False" >> recettes/local_settings.py
        echo "SECURE_HSTS_INCLUDE_SUBDOMAINS_ = False" >> recettes/local_settings.py
        echo "SECURE_HSTS_PRELOAD_ = False" >> recettes/local_settings.py
        echo "SECURE_SSL_REDIRECT_ = False" >> recettes/local_settings.py
        echo "SESSION_COOKIE_SECURE_ = False" >> recettes/local_settings.py
        echo "CSRF_COOKIE_SECURE_ = False" >> recettes/local_settings.py
        echo "SECURE_HSTS_SECONDS_ = 0" >> recettes/local_settings.py
    - name: Run Checks
      run: |
        python manage.py check
    - name: Run Deployment Checks for SSL
      run: |
        python manage.py check --deploy
    - name: Run Tests
      run: |
        python manage.py test
    - name: Coverage
      run: |
        coverage run manage.py test app.tests
    - name: Uploading codecov reports
      run: |
        bash <(curl -s https://codecov.io/bash) -v || echo 'Codecov failed to upload'
