name: Django CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create local settings placeholder
        run: |
          echo "situation = 'ci' " > recettes/env.py
      - name: Cleaning before db init
        run: |
          rm db.sqlite3
          rm -r app/__pycache__
          rm -r app/migrations
      - name: Create DB
        run: |
          python manage.py makemigrations
          python manage.py migrate
      - name: Run Checks
        run: |
          python manage.py check
      - name: Run Deployment Checks for SSL
        run: |
          python manage.py check --deploy
      - name: Run Tests
        run: |
          python manage.py test
      - name: Coverage
        run: |
          coverage run manage.py test app.tests
      - name: Uploading codecov reports
        run: |
          bash <(curl -s https://codecov.io/bash) -v || echo 'Codecov failed to upload'
